- css.md
@tgolen 
Added rule for concatenating strings to prevent CSScomb issues and added another rule to the CSScomb configuration which enables sorting declarations alphabetically.
> Add concatenation guideline and CSScomb configuration rule

- java.md
@flodnv @nkuoch 
Adding a few things related to lambdas, let me know if it makes sense to you.
> Coding guidelines for lambdas

- php.md
> lowerCamelCase

- cpp.md
@michaelkitson 
cc @tylerkaraszewski @mattabullock @yuwenmemon 
Fixes https://github.com/Expensify/Expensify/issues/11405
Let me know if I missed anything.
> C++ Style Guide

- README.md
- cpp.md
@michaelkitson please review
cc @mattabullock @yuwenmemon @tylerkaraszewski 
Fixes https://github.com/Expensify/Expensify/issues/20578
> Update cpp style to include documentation section

- javascript.md
@iwiznia 
This is going with https://github.com/Expensify/Web-Expensify/pull/11753
cc @tgolen @nkuoch @yuwenmemon @flodnv
> Refresh javascript.md

- php.md
Updated `$myStrin` to `$myString`
> Tiny typo fix

- php.md
I think this would be a good addition to the PHP style guide related to namespaces.
What do you guys think?
> Add guideline about using namespaces in PHP

- php.md
@michaelkitson @tgolen @iwiznia @fnwbr @mea36 @tylerkaraszewski @nkuoch @romuloab @cead22 @timszot @robertjchen @mattabullock (just tagging everyone who works with PHP)
please +1 and merge
> Update php style to include explicit case rule

- javascript.md
@tgolen please review
no tests no qa
> Add pragmatic JS tips

- css.md
@shawnborton 
cc @Expensify/web @tgolen 
This goes with the corresponding Web PR, let's discuss over there and I'll update this PR when necessary.
> Add sass-lint configuration & update CSS guidelines

- javascript.md
@yuwenmemon Can you please review this? Let me know if I missed something!
Also CC @cead22 just so you're FYI.
> Adding some React specific style guidelines that we follow

- general.md
@cead22 @quinthar @mcnamamj Can you please review this?
> Adding a section about simplicity

- php.md
Fixes https://github.com/Expensify/Style-Guide/issues/27
> Add section about type declarations

- general.md
- php.md
@fnwbr , could you review this?
Updated style guide for boolean variables as per [comment](https://github.com/Expensify/Web-Expensify/pull/16683#discussion_r106454396)
1. None
> Updated style guide for Boolean variables

- javascript.md
@fnwbr Would you please review this? Saw this in the React docs over the weekend.
> Add better inline ternary styles

- php.md
@mattabullock 
This contradicted what we actually do.
> Update php string style

- php.md
@iwiznia, will you please review this?
> PHP: Add null coalescing operator / new line after opening tag

- php.md
@anyone
Magic methods have caused bugs in that past that have proven tricky to diagnose and they still cause confusion today.
> Update guidelines to state that we must not use magic methods

- javascript.md
- php.md
> Update guidelines to prevent token alignment

- php.md
> Indent the sql properly

- javascript.md
cc @iwiznia Coming from https://github.com/Expensify/Web-Expensify/pull/18969#discussion_r147510667
> Add event handler name conventions

- cpp.md
@cead22 please review
cc @mattabullock @pecanoro
> Clarify what to do with function docs

- README.md
- swift.md
Adds swift Style Guide from our internal wiki 🎉
> Add swift style guide

- php.md
I thought this was a convention of us, but it's not in the style guide and I see we don't do this everywhere. So formalizing it here.
/cc @Expensify/engineering
> Add blurb about indentation on templates

- php.md
> Document how we want to treat @throws tags

- sql.md
@cead22 please review
cc @Expensify/engineering 
Some small clarifications to account for latest global style changes as well as common confusions.
> Clarify SQL styles
